config/routes.rb
RubyNorth::Application.routes.draw do

  resources :orders
  resources :orderdetails
  resources :shippers
  root :to => 'employees#index'
  resources :employees
  match 'employees/:id/show_photo' => 'employees#show_photo'
  match 'DbTest/parseOrders' => 'DbTest#parseOrders'
  match 'DbTest/parseOrderDetails' => 'DbTest#parseOrderDetails'
  match 'DbTest/orders_by_country' => 'DbTest#orders_by_country'
  match 'DbTest/avg_time_by_year' => 'DbTest#avg_time_by_year'
  match 'DbTest/products_by_supplier' => 'DbTest#products_by_supplier'
  match 'DbTest/amount_by_day' => 'DbTest#amount_by_day'
  match 'DbTest/amount_by_country' => 'DbTest#amount_by_country'
  match 'DbTest/product_val_by_supplieryear' => 'DbTest#product_val_by_supplieryear'

end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
  self.primary_key = 'ShipperID'
  self.table_name = 'Shippers'
  # attr_accessible :title, :body
end

app/controllers/shippers_controller.rb
class ShippersController < ApplicationController
  # GET /shippers
  # GET /shippers.json
  def index
    @shippers = Shipper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shippers }
    end
  end

  # GET /shippers/1
  # GET /shippers/1.json
  def show
    @shipper = Shipper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shipper }
    end
  end

  # GET /shippers/new
  # GET /shippers/new.json
  def new
    @shipper = Shipper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shipper }
    end
  end

  # GET /shippers/1/edit
  def edit
    @shipper = Shipper.find(params[:id])
  end

  # POST /shippers
  # POST /shippers.json
  def create
    @shipper = Shipper.new(params[:shipper])

    respond_to do |format|
      if @shipper.save
        format.html { redirect_to @shipper, :notice => 'Shipper was successfully created.' }
        format.json { render :json => @shipper, :status => :created, :location => @shipper }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shipper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shippers/1
  # PUT /shippers/1.json
  def update
    @shipper = Shipper.find(params[:id])

    respond_to do |format|
      if @shipper.update_attributes(params[:shipper])
        format.html { redirect_to @shipper, :notice => 'Shipper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shipper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shippers/1
  # DELETE /shippers/1.json
  def destroy
    @shipper = Shipper.find(params[:id])
    @shipper.destroy

    respond_to do |format|
      format.html { redirect_to shippers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/views/shippers/_form.html.erb
<%= form_for(@shipper) do |f| %>
  <% if @shipper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipper.errors.count, "error") %> prohibited this shipper from being saved:</h2>

      <ul>
      <% @shipper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shippers/edit.html.erb
<h1>Editing shipper</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipper %> |
<%= link_to 'Back', shippers_path %>

app/views/shippers/index.html.erb
<h1>Listing shippers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shippers.each do |shipper| %>
  <tr>
    <td><%= link_to 'Show', shipper %></td>
    <td><%= link_to 'Edit', edit_shipper_path(shipper) %></td>
    <td><%= link_to 'Destroy', shipper, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shipper', new_shipper_path %>

app/views/shippers/new.html.erb
<h1>New shipper</h1>

<%= render 'form' %>

<%= link_to 'Back', shippers_path %>

app/views/shippers/show.html.erb
<p id="notice"><%= notice %></p>


<%= @shipper.ShipperID %>
<%= link_to 'Edit', edit_shipper_path(@shipper) %> |
<%= link_to 'Back', shippers_path %>